/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Root
         * @description 返回API信息
         *
         *     Returns:
         *         API基本信息
         */
        get: operations["api_root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description 获取前端配置信息（包括 Google Maps API Key）
         *
         *     Returns:
         *         配置信息
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Conversations
         * @description 获取用户的所有对话列表
         *
         *     Args:
         *         user_id: 用户ID
         *
         *     Returns:
         *         对话摘要列表
         */
        get: operations["get_all_conversations_api_conversations__user_id__get"];
        put?: never;
        /**
         * Create Conversation
         * @description 创建新对话
         *
         *     Args:
         *         user_id: 用户ID
         *         request: 创建对话请求
         *
         *     Returns:
         *         创建的对话数据
         */
        post: operations["create_conversation_api_conversations__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取单个对话的完整信息（包含所有消息）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         完整的对话数据
         */
        get: operations["get_conversation_api_conversations__user_id___conversation_id__get"];
        /**
         * Update Conversation
         * @description 更新对话信息（如标题、模型等）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         request: 更新请求
         *
         *     Returns:
         *         更新后的对话数据
         */
        put: operations["update_conversation_api_conversations__user_id___conversation_id__put"];
        post?: never;
        /**
         * Delete Conversation
         * @description 删除对话
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         成功状态
         */
        delete: operations["delete_conversation_api_conversations__user_id___conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description 向对话添加消息
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         request: 添加消息请求
         *
         *     Returns:
         *         成功状态
         */
        post: operations["add_message_api_conversations__user_id___conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation Preferences
         * @description 获取对话的偏好设置（优先从内存缓存获取）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         偏好设置字典
         */
        get: operations["get_conversation_preferences_api_conversations__user_id___conversation_id__preferences_get"];
        /**
         * Update Conversation Preferences
         * @description 更新对话的偏好设置（同时更新内存缓存和持久化层）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         preferences_data: 偏好设置字典
         *
         *     Returns:
         *         更新后的偏好设置（从内存缓存返回）
         */
        put: operations["update_conversation_preferences_api_conversations__user_id___conversation_id__preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process User Request
         * @description 处理用户请求的统一接口
         *     融合了 LLM 意图识别、偏好提取、确认流程
         *
         *     这个接口会自动处理：
         *     - 使用 LLM 进行意图识别和生成回复
         *     - 如果是推荐餐厅请求：触发推荐流程
         *     - 如果是普通对话：返回 LLM 的回复
         *
         *     Args:
         *         query_data: {"query": "用户查询", "user_id": "用户ID（可选）", "conversation_history": "对话历史（可选）"}
         *
         *     Returns:
         *         根据处理结果返回不同的响应：
         *         - 如果是 LLM 回复：返回 llm_reply 字段
         *         - 如果是确认请求：返回确认请求对象
         *         - 如果是任务创建：返回任务ID
         *         - 如果是修改请求：返回修改提示
         */
        post: operations["process_user_request_api_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process User Request Stream
         * @description 流式处理用户请求（用于逐字显示回复）
         *
         *     Args:
         *         query_data: {"query": "用户查询", "user_id": "用户ID（可选）", "conversation_history": "对话历史（可选）"}
         *
         *     Returns:
         *         Server-Sent Events (SSE) 流，逐字返回 GPT-4 的回复
         */
        post: operations["process_user_request_stream_api_process_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description 获取任务状态
         *     前端通过轮询此接口获取任务进度和最终结果
         *
         *     Args:
         *         task_id: 任务ID
         *         user_id: 用户ID（可选，提供后更精确查找）
         *         conversation_id: 会话ID（可选，提供后更精确查找）
         *
         *     Returns:
         *         任务状态信息，包括：
         *         - status: "processing" | "completed" | "error"
         *         - progress: 0-100的进度值
         *         - message: 当前状态消息
         *         - result: 推荐结果（任务完成时）
         *         - error: 错误信息（任务失败时）
         */
        get: operations["get_task_status_api_status__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Preferences Endpoint
         * @description 更新用户偏好设置
         *
         *     Args:
         *         preferences_data: 包含用户偏好的字典，格式：
         *         {
         *             "user_id": "用户ID（可选，默认'default'）",
         *             "restaurantTypes": ["casual", "fine-dining"],
         *             "flavorProfiles": ["spicy", "savory"],
         *             "diningPurpose": "friends",
         *             "budgetRange": {"min": 20, "max": 60, "currency": "SGD", "per": "person"},
         *             "location": "Chinatown"
         *         }
         *
         *     Returns:
         *         更新后的偏好设置
         */
        post: operations["update_preferences_endpoint_api_update_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-preferences/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Preferences Endpoint
         * @description 获取用户当前的偏好设置
         *
         *     Args:
         *         user_id: 用户ID
         *
         *     Returns:
         *         用户偏好设置，包括：
         *         - user_id: 用户ID
         *         - preferences: 偏好设置字典
         */
        get: operations["get_user_preferences_endpoint_api_user_preferences__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查
         *
         *     Returns:
         *         服务健康状态
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/api-playground/generate-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Api Playground Input */
        post: operations["generate_api_playground_input_internal_debug_api_playground_generate_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Behavior */
        get: operations["list_behavior_internal_debug_behavior_tests_get"];
        put?: never;
        /** Start Behavior */
        post: operations["start_behavior_internal_debug_behavior_tests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Track */
        post: operations["start_track_internal_debug_behavior_tests_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Behavior */
        get: operations["get_behavior_internal_debug_behavior_tests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Endpoint */
        post: operations["explain_endpoint_internal_debug_behavior_tests__run_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_internal_debug_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_internal_debug_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_internal_debug_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_internal_debug_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/generate-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Unit Input */
        post: operations["generate_unit_input_internal_debug_unit_tests_generate_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Unit */
        post: operations["run_unit_internal_debug_unit_tests_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_internal_debug_unit_tests_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddMessageRequest
         * @description 添加消息请求
         */
        AddMessageRequest: {
            /** Content */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | Record<string, never> | null;
            /** Role */
            role: string;
        };
        /** ApiInfoResponseAPI */
        ApiInfoResponseAPI: {
            /** Message */
            message: string;
            /** Version */
            version: string;
        };
        /** ApiPlaygroundInputGenerateRequest */
        ApiPlaygroundInputGenerateRequest: {
            /** Method */
            method?: string | null;
            /**
             * Mode
             * @default schema
             */
            mode: string;
            /** Path */
            path?: string | null;
            /** Schema */
            schema?: Record<string, never>;
            /** Summary */
            summary?: string | null;
        };
        /** BehaviorTestCreateRequest */
        BehaviorTestCreateRequest: {
            /**
             * Auto Confirm
             * @default true
             */
            auto_confirm: boolean;
            /**
             * Confirm Message
             * @default Yes, that's correct
             */
            confirm_message: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Max Wait Seconds
             * @default 90
             */
            max_wait_seconds: number;
            /**
             * Poll Interval Ms
             * @default 500
             */
            poll_interval_ms: number;
            /** Query */
            query: string;
            /**
             * Use Online Agent
             * @default false
             */
            use_online_agent: boolean;
            /**
             * User Id
             * @default debug_user
             */
            user_id: string;
        };
        /** BehaviorTrackRequest */
        BehaviorTrackRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Max Wait Seconds
             * @default 90
             */
            max_wait_seconds: number;
            /**
             * Poll Interval Ms
             * @default 500
             */
            poll_interval_ms: number;
            /** Task Id */
            task_id: string;
            /** User Id */
            user_id?: string | null;
        };
        /** BudgetRangeInputAPI */
        BudgetRangeInputAPI: {
            /**
             * Currency
             * @default SGD
             */
            currency: string;
            /**
             * Max
             * @default 60
             */
            max: number | null;
            /**
             * Min
             * @default 20
             */
            min: number | null;
            /**
             * Per
             * @default person
             */
            per: string;
        };
        /** ConfirmationRequestAPI */
        ConfirmationRequestAPI: {
            /** Message */
            message: string;
            /**
             * Needs Confirmation
             * @default true
             */
            needs_confirmation: boolean;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /**
         * ConversationData
         * @description 完整对话数据
         */
        ConversationData: {
            /** Id */
            id: string;
            /** Last Message */
            last_message: string;
            /** Messages */
            messages: components["schemas"]["MessageData"][];
            /** Model */
            model: string;
            /** Timestamp */
            timestamp: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * ConversationSummary
         * @description 对话摘要（用于列表）
         */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Last Message */
            last_message: string;
            /** Message Count */
            message_count: number;
            /** Model */
            model: string;
            /** Timestamp */
            timestamp: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * CreateConversationRequest
         * @description 创建对话请求
         */
        CreateConversationRequest: {
            /**
             * Model
             * @default RestRec
             */
            model: string;
            /** Title */
            title?: string | null;
        };
        /** DebugLoginRequest */
        DebugLoginRequest: {
            /** Token */
            token: string;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Mode
             * @default nl_explain
             */
            mode: string;
        };
        /** FrontendConfigResponseAPI */
        FrontendConfigResponseAPI: {
            /** Googlemapsapikey */
            googleMapsApiKey: string;
        };
        /** GenericSuccessResponseAPI */
        GenericSuccessResponseAPI: {
            /** Message */
            message: string;
            /** Success */
            success: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponseAPI */
        HealthResponseAPI: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * MessageData
         * @description 消息数据
         */
        MessageData: {
            /** Content */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | Record<string, never> | null;
            /** Role */
            role: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** PreferencesResponseAPI */
        PreferencesResponseAPI: {
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /** ProcessMessageAPI */
        ProcessMessageAPI: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** ProcessRequestAPI */
        ProcessRequestAPI: {
            /** Conversation History */
            conversation_history?: components["schemas"]["ProcessMessageAPI"][] | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Query */
            query: string;
            /**
             * Use Online Agent
             * @default false
             */
            use_online_agent: boolean;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** ProcessStreamRequestAPI */
        ProcessStreamRequestAPI: {
            /** Conversation History */
            conversation_history?: components["schemas"]["ProcessMessageAPI"][] | null;
            /** Query */
            query: string;
            /**
             * Use Online Agent
             * @default false
             */
            use_online_agent: boolean;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** RecommendationResponseAPI */
        RecommendationResponseAPI: {
            confirmation_request?: components["schemas"]["ConfirmationRequestAPI"] | null;
            /** Intent */
            intent?: string | null;
            /** Llm Reply */
            llm_reply?: string | null;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            } | Record<string, never> | null;
            /** Restaurants */
            restaurants: components["schemas"]["RestaurantAPI"][];
            /** Thinking Steps */
            thinking_steps?: components["schemas"]["ThinkingStepAPI"][] | null;
        };
        /** RestaurantAPI */
        RestaurantAPI: {
            /** Address */
            address?: string | null;
            /** Area */
            area?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Distance Or Walk Time */
            distance_or_walk_time?: string | null;
            /** Flavor Match */
            flavor_match?: string[] | null;
            /** Gps Coordinates */
            gps_coordinates?: {
                [key: string]: number;
            } | null;
            /** Highlights */
            highlights?: string[] | null;
            /** Id */
            id: string;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Open Hours Note */
            open_hours_note?: string | null;
            /** Phone */
            phone?: string | null;
            /** Price */
            price?: string | null;
            /** Price Per Person Sgd */
            price_per_person_sgd?: string | null;
            /** Purpose Match */
            purpose_match?: string[] | null;
            /** Rating */
            rating?: number | null;
            /** Reason */
            reason?: string | null;
            /** Reference */
            reference?: string | null;
            /** Reviews Count */
            reviews_count?: number | null;
            /** Sources */
            sources?: {
                [key: string]: string;
            } | null;
            /** Type */
            type?: string | null;
            /** Why */
            why?: string | null;
        };
        /** TaskStatusAPI */
        TaskStatusAPI: {
            /** Error */
            error?: string | null;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            result?: components["schemas"]["RecommendationResponseAPI"] | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
        };
        /** ThinkingStepAPI */
        ThinkingStepAPI: {
            /** Description */
            description: string;
            /** Details */
            details?: string | null;
            /** Status */
            status: string;
            /** Step */
            step: string;
        };
        /** UnitInputGenerateRequest */
        UnitInputGenerateRequest: {
            /**
             * Mode
             * @default schema
             */
            mode: string;
            /** Unit Name */
            unit_name: string;
        };
        /** UnitRunRequest */
        UnitRunRequest: {
            /** Input Data */
            input_data?: Record<string, never> | null;
            /**
             * Input Mode
             * @default manual
             */
            input_mode: string;
            /** Unit Name */
            unit_name: string;
            /**
             * Use Llm Generation
             * @default false
             */
            use_llm_generation: boolean;
        };
        /**
         * UpdateConversationRequest
         * @description 更新对话请求
         */
        UpdateConversationRequest: {
            /** Model */
            model?: string | null;
            /** Title */
            title?: string | null;
        };
        /** UpdatePreferencesRequestAPI */
        UpdatePreferencesRequestAPI: {
            /**
             * @default {
             *       "currency": "SGD",
             *       "max": 60,
             *       "min": 20,
             *       "per": "person"
             *     }
             */
            budgetRange: components["schemas"]["BudgetRangeInputAPI"];
            /**
             * Diningpurpose
             * @default any
             */
            diningPurpose: string;
            /**
             * Flavorprofiles
             * @default [
             *       "any"
             *     ]
             */
            flavorProfiles: string[];
            /**
             * Location
             * @default any
             */
            location: string;
            /**
             * Restauranttypes
             * @default [
             *       "any"
             *     ]
             */
            restaurantTypes: string[];
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** UpdatePreferencesResponseAPI */
        UpdatePreferencesResponseAPI: {
            /** Message */
            message: string;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /** UserPreferencesResponseAPI */
        UserPreferencesResponseAPI: {
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiInfoResponseAPI"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendConfigResponseAPI"];
                };
            };
        };
    };
    get_all_conversations_api_conversations__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__user_id___conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_conversations__user_id___conversation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__user_id___conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericSuccessResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_api_conversations__user_id___conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericSuccessResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_preferences_api_conversations__user_id___conversation_id__preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_preferences_api_conversations__user_id___conversation_id__preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_user_request_api_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_user_request_stream_api_process_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessStreamRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_status__task_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
                conversation_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_endpoint_api_update_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_preferences_endpoint_api_user_preferences__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseAPI"];
                };
            };
        };
    };
    generate_api_playground_input_internal_debug_api_playground_generate_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiPlaygroundInputGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_behavior_internal_debug_behavior_tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_behavior_internal_debug_behavior_tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BehaviorTestCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_track_internal_debug_behavior_tests_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BehaviorTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_behavior_internal_debug_behavior_tests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_endpoint_internal_debug_behavior_tests__run_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_internal_debug_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_internal_debug_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_internal_debug_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    session_info_internal_debug_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_unit_input_internal_debug_unit_tests_generate_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitInputGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_unit_internal_debug_unit_tests_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_internal_debug_unit_tests_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
